[0m[[0m[31merror[0m] [0m[0mio.grpc.StatusRuntimeException: UNAVAILABLE: io exception[0m
[0m[[0m[31merror[0m] [0m[0m	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:271)[0m
[0m[[0m[31merror[0m] [0m[0m	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:252)[0m
[0m[[0m[31merror[0m] [0m[0m	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:131)[0m
[0m[[0m[31merror[0m] [0m[0m	at scalapb.grpc.ClientCalls$.blockingUnaryCall(ClientCalls.scala:15)[0m
[0m[[0m[31merror[0m] [0m[0m	at com.hellogrpc.hello.lambdaQueryGrpc$lambdaQueryBlockingStub.checkLogBool(lambdaQueryGrpc.scala:54)[0m
[0m[[0m[31merror[0m] [0m[0m	at main$package$.main(main.scala:21)[0m
[0m[[0m[31merror[0m] [0m[0m	at main$package.main(main.scala)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/java.lang.reflect.Method.invoke(Method.java:577)[0m
[0m[[0m[31merror[0m] [0m[0m	at sbt.Run.invokeMain(Run.scala:143)[0m
[0m[[0m[31merror[0m] [0m[0m	at sbt.Run.execute$1(Run.scala:93)[0m
[0m[[0m[31merror[0m] [0m[0m	at sbt.Run.$anonfun$runWithLoader$5(Run.scala:120)[0m
[0m[[0m[31merror[0m] [0m[0m	at sbt.Run$.executeSuccess(Run.scala:186)[0m
[0m[[0m[31merror[0m] [0m[0m	at sbt.Run.runWithLoader(Run.scala:120)[0m
[0m[[0m[31merror[0m] [0m[0m	at sbt.Defaults$.$anonfun$bgRunTask$6(Defaults.scala:1980)[0m
[0m[[0m[31merror[0m] [0m[0m	at sbt.Defaults$.$anonfun$termWrapper$2(Defaults.scala:1919)[0m
[0m[[0m[31merror[0m] [0m[0m	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)[0m
[0m[[0m[31merror[0m] [0m[0m	at scala.util.Try$.apply(Try.scala:213)[0m
[0m[[0m[31merror[0m] [0m[0m	at sbt.internal.BackgroundThreadPool$BackgroundRunnable.run(DefaultBackgroundJobService.scala:369)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/java.lang.Thread.run(Thread.java:833)[0m
[0m[[0m[31merror[0m] [0m[0mCaused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:444[0m
[0m[[0m[31merror[0m] [0m[0mCaused by: java.net.ConnectException: Connection refused: no further information[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/sun.nio.ch.Net.pollConnect(Native Method)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:946)[0m
[0m[[0m[31merror[0m] [0m[0m	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)[0m
[0m[[0m[31merror[0m] [0m[0m	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)[0m
[0m[[0m[31merror[0m] [0m[0m	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:710)[0m
[0m[[0m[31merror[0m] [0m[0m	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)[0m
[0m[[0m[31merror[0m] [0m[0m	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)[0m
[0m[[0m[31merror[0m] [0m[0m	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)[0m
[0m[[0m[31merror[0m] [0m[0m	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)[0m
[0m[[0m[31merror[0m] [0m[0m	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)[0m
[0m[[0m[31merror[0m] [0m[0m	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/java.lang.Thread.run(Thread.java:833)[0m
[0m[[0m[31merror[0m] [0m[0m(Compile / [31mrun[0m) io.grpc.StatusRuntimeException: UNAVAILABLE: io exception[0m
